"""The physical network-operation ledger (EPA C1, READY-005, fixes P0.7).

Before C1 there was no row anywhere that stood for *one physical thing
that happened on the wire*. ``request_attempts`` is a **logical**
attempt: it is workspace-owned, one row per attempted target, and it
carries transport-observed byte counts (``main_document_bytes`` /
``subresource_bytes``, EPA B6). That is the right shape for "did this
tenant's target get fetched" and the wrong shape for "what did the fleet
actually spend": a single browser navigation can serve two workspaces
watching the same competitor URL, a retry is a second physical fetch of
the same logical attempt, and a browser subresource is a physical fetch
with no logical attempt of its own at all. Costing off the logical row
therefore either double-counts or loses money, and no amount of
after-the-fact SQL can recover a fact that was never recorded.

This module records that missing fact as **three separate append-only
tables**, deliberately not one mutable row:

``network_operations``
    The physical operation. **Immutable intent** fields are written at
    open (before the request is dispatched — ``network_request_id`` is
    generated by the caller *first*, so the identity exists even if the
    process dies mid-flight); **immutable outcome** fields are written
    exactly once at close. ``closed_at`` is what makes "exactly once" a
    checkable predicate: a ``BEFORE UPDATE`` trigger rejects any update
    to a row whose ``closed_at`` is already set, and rejects any update
    that touches an intent column at all, open or closed.

    The row is **fleet-owned**: it has NO ``workspace_id`` column. That
    is the whole design. A physical fetch is not owned by a tenant —
    tenant ownership is a *derived allocation* of it, and putting a
    ``workspace_id`` here would force a lie the first time one fetch
    serves two workspaces.

``network_operation_allocations``
    The tenant-visible half, and the ONLY one of the three with
    row-level security. One row per (operation, workspace): the
    ``fraction`` of the operation attributed to that workspace and the
    ``allocated_cost_minor_units`` that follows from it. Fractions are
    exact scaled integers (parts per billion, :data:`FRACTION_SCALE`),
    never floats. Rounding uses :func:`allocate_cost_largest_remainder`
    so the parts sum EXACTLY to the operation's cost, and a **deferred**
    constraint trigger re-checks that total at COMMIT. A single-tenant
    operation gets exactly one row at fraction ``1.0``.

``network_operation_settlements``
    Append-only provider reconciliation facts, written later by C5 when
    the provider's own usage record arrives. A correction never rewrites
    history: it appends a higher ``settlement_version``, and "current
    reconciled cost" is the latest version. UPDATE and DELETE are both
    rejected by a trigger.

Money
-----
Every amount in this ledger is an **integer in currency minor units**
paired with an ISO-4217 ``currency`` code — the ``app_shared.money``
§19 contract ("money is never a float") expressed as scaled integers so
there is no Decimal-vs-float ambiguity at any boundary, in the ORM, in
raw SQL, or in JSON. :class:`app_shared.money.Money` (``NUMERIC(18,4)``)
stays the right type for *prices observed on a page*; a per-request
provider charge is a counted quantity of minor units, and counting it as
one keeps addition exact and the deferred total constraint decidable.

The one figure that is a **rate** rather than an amount —
``billing_rate_micro_units`` — is scaled by a further
:data:`BILLING_RATE_SCALE` (millionths of a minor unit per one
``billing_unit``) precisely so that sub-cent rates (``$0.0007`` per
request is a real proxy price) survive as exact integers instead of
rounding to zero.

RLS and who writes what
-----------------------
Only ``network_operation_allocations`` gets a policy
(:func:`app_shared.models.rls.emit_rls_policy`, ENABLE + FORCE, applied
in the same migration that creates the table). The other two tables are
fleet facts with no ``workspace_id`` to scope by, and are listed as
annotated ``GAP`` entries in ``scripts/rls_table_manifest.txt`` so
``provision_db_roles.py --verify`` reads the decision out loud on every
run rather than letting it go quiet.

**The allocation-total constraint trigger runs as the invoker**, and it
must aggregate every workspace's share of one operation. Under FORCE
RLS a tenant connection would see only its own row and compute a
spurious shortfall, so an allocation SET MUST be written on the
sanctioned BYPASSRLS system seam (``crawmatic_auth`` /
``get_system_session``) — the same seam the scheduler's cross-tenant
due-rule claim already uses. This is deliberate, not an oversight: a
tenant has no business writing a cross-tenant cost split, and the
trigger failing closed if one tries is the correct outcome.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from enum import StrEnum
from typing import Sequence

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Date,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app_shared.enums import enum_column
from app_shared.ids import new_uuid7
from app_shared.models.base import Base, TZDateTime, WorkspaceScopedBase

#: Allocation fractions are stored as parts per billion — an exact scaled
#: integer, never a float and never a bare NUMERIC. ``1.0`` is
#: ``1_000_000_000``. A billion parts is enough to express any realistic
#: split (a 1-in-a-billion share of a request is not a thing) while
#: staying far inside ``bigint``.
FRACTION_SCALE = 1_000_000_000

#: ``billing_rate_micro_units`` is expressed in MILLIONTHS of one
#: currency minor unit per one ``billing_unit``. A ``$3.00/GB`` proxy
#: rate is ``300 * 1_000_000``; a ``$0.0007`` per-request rate is
#: ``70_000`` — exact, where plain minor units would round it to zero.
BILLING_RATE_SCALE = 1_000_000


class NetworkTransport(StrEnum):
    """How the physical operation reached the origin.

    ``DIRECT``  — straight from the fleet's own egress IP, no proxy.
    ``PROXY``   — through a paid proxy provider (the billed path).
    ``BROWSER`` — a real browser navigation; its subresource fetches are
                  themselves ``BROWSER`` operations carrying
                  ``parent_operation_id``.
    """

    DIRECT = "DIRECT"
    PROXY = "PROXY"
    BROWSER = "BROWSER"


class SettlementMethod(StrEnum):
    """How a settlement's reconciled cost was derived.

    ``PRO_RATA_BYTES`` — the provider billed a period, not a request;
                         this operation's share was apportioned by its
                         transport-observed bytes.
    ``EXACT``          — the provider's usage record names this
                         operation directly.
    ``CORRECTION``     — a later restatement of an earlier version. It
                         APPENDS; it never edits the version it corrects.
    """

    PRO_RATA_BYTES = "PRO_RATA_BYTES"
    EXACT = "EXACT"
    CORRECTION = "CORRECTION"


def allocate_cost_largest_remainder(
    total_minor_units: int, weights: Sequence[int]
) -> list[int]:
    """Split ``total_minor_units`` across ``weights`` so the parts sum EXACTLY.

    The largest-remainder (Hamilton) method: floor every share, then hand
    the leftover units back one at a time to the shares with the largest
    discarded remainders (ties broken by position, so the result is
    deterministic for a given input order).

    This is the rounding rule the deferred allocation-total constraint
    assumes. Naive per-share rounding loses a minor unit on the classic
    ``100 / 3`` case (``33 + 33 + 33 = 99``) — and a ledger that loses a
    unit per multi-tenant fetch is a ledger that cannot be reconciled
    against a provider invoice.

    Integers only, both arguments: passing a ``float`` raises
    ``TypeError`` rather than silently reintroducing binary-fraction
    error into money (§19, the same posture as
    :func:`app_shared.money.parse_money`).
    """
    if isinstance(total_minor_units, bool) or not isinstance(total_minor_units, int):
        raise TypeError(
            "total_minor_units must be an int of currency minor units, "
            f"got {type(total_minor_units)!r} — money is never a float"
        )
    if total_minor_units < 0:
        raise ValueError(f"total_minor_units must be non-negative: {total_minor_units!r}")

    weight_list = list(weights)
    if not weight_list:
        raise ValueError("weights must be non-empty — an operation with no allocation "
                         "is an unowned cost")
    for weight in weight_list:
        if isinstance(weight, bool) or not isinstance(weight, int):
            raise TypeError(
                f"weights must be ints, got {type(weight)!r} — fractions are exact "
                "scaled integers, never floats"
            )
        if weight < 0:
            raise ValueError(f"weights must be non-negative: {weight!r}")

    weight_total = sum(weight_list)
    if weight_total <= 0:
        raise ValueError("weights must sum to a positive value")

    floors = [(total_minor_units * weight) // weight_total for weight in weight_list]
    remainders = [
        (total_minor_units * weight) - floor * weight_total
        for weight, floor in zip(weight_list, floors, strict=True)
    ]
    leftover = total_minor_units - sum(floors)
    # Hand the leftover units to the largest remainders first; `-index`
    # is not used — a stable sort on (-remainder, index) keeps the result
    # deterministic and independent of Python's sort internals.
    order = sorted(range(len(weight_list)), key=lambda i: (-remainders[i], i))
    for i in order[:leftover]:
        floors[i] += 1
    return floors


class NetworkOperation(Base):
    """``network_operations`` — ONE physical thing that happened on the wire.

    Fleet-owned (no ``workspace_id``); append-only by trigger. ``id`` is
    the ordinary surrogate row key every :class:`Base` subclass carries;
    ``network_request_id`` is the **operation identity** — generated by
    the caller BEFORE dispatch, unique, and the key every other table in
    this ledger (and ``request_attempts.network_operation_id``) points
    at. Referencing the pre-dispatch identity rather than the surrogate
    is what lets a writer stamp the identity onto in-flight telemetry
    without first round-tripping the insert.

    ``retry_parent_id`` chains a retry to the physical operation it
    re-attempts; ``parent_operation_id`` chains a browser subresource to
    the navigation that pulled it in. Both point at
    ``network_request_id`` — a retry of a retry, and a subresource of a
    subresource, are both representable.

    ``authorization_id`` is the C3 authorization this operation was
    dispatched under. It is nullable and carries NO foreign key here:
    the authorization table lands in C3, and a schema that cannot be
    applied before its dependency exists is a schema that blocks the
    lane. Making the FK real (and, separately, proving every operation
    HAS one) belongs to C3/C4 — a nullable column is not a coverage
    claim.
    """

    __tablename__ = "network_operations"
    __table_args__ = (
        # No explicit UniqueConstraint here: `network_request_id` carries
        # `unique=True` on the column itself, which the naming convention
        # renders as `uq_network_operations_network_request_id` (40 chars,
        # inside Postgres's 63-byte identifier limit). Declaring both
        # would emit the same constraint twice.
        ForeignKeyConstraint(
            ["retry_parent_id"],
            ["network_operations.network_request_id"],
            name="fk_no_retry_parent_id_network_operations",
        ),
        ForeignKeyConstraint(
            ["parent_operation_id"],
            ["network_operations.network_request_id"],
            name="fk_no_parent_operation_id_network_operations",
        ),
        CheckConstraint(
            "estimated_cost_minor_units IS NULL OR estimated_cost_minor_units >= 0",
            name="no_estimated_cost_non_negative",
        ),
        CheckConstraint(
            "billing_rate_micro_units IS NULL OR billing_rate_micro_units >= 0",
            name="no_billing_rate_non_negative",
        ),
        CheckConstraint(
            "estimated_cost_minor_units IS NULL OR currency IS NOT NULL",
            name="no_cost_requires_currency",
        ),
        CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name="no_currency_is_iso4217",
        ),
        Index("ix_network_operations_provider_created_at", "provider", "created_at"),
        Index("ix_network_operations_scrape_job_id", "scrape_job_id"),
        Index(
            "ix_network_operations_canonical_url_hash_created_at",
            "canonical_url_hash",
            "created_at",
        ),
    )

    # --- immutable intent, written at open --------------------------------
    #: Generated by the caller BEFORE dispatch, so the operation has an
    #: identity even if the process dies before the row is closed.
    network_request_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), nullable=False, unique=True, default=new_uuid7
    )
    retry_parent_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), nullable=True
    )
    #: Browser subresources point at the navigation that pulled them in.
    parent_operation_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), nullable=True
    )
    #: Plain nullable id, NO foreign key: an operation can be a fleet-side
    #: probe with no scrape job at all, and adding a real FK to a
    #: workspace-owned, monthly-partitioned parent would drag tenant
    #: ownership back into a fleet row.
    scrape_job_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), nullable=True
    )
    canonical_url_hash: Mapped[str] = mapped_column(Text(), nullable=False)
    domain: Mapped[str] = mapped_column(Text(), nullable=False)
    http_method: Mapped[str] = mapped_column(
        Text(), nullable=False, default="GET", server_default=text("'GET'")
    )
    region: Mapped[str | None] = mapped_column(Text(), nullable=True)
    provider: Mapped[str] = mapped_column(Text(), nullable=False)
    provider_account: Mapped[str | None] = mapped_column(Text(), nullable=True)
    transport: Mapped[NetworkTransport] = enum_column(NetworkTransport, nullable=False)
    #: The C3 authorization this dispatch was made under. See the class
    #: docstring for why there is no FK and why nullable is not a
    #: coverage claim.
    authorization_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True), nullable=True
    )
    #: Opaque version tags (the `classifier_version` precedent): text, so
    #: a later change of versioning scheme never silently reinterprets an
    #: old decision.
    entitlement_version: Mapped[str | None] = mapped_column(Text(), nullable=True)
    budget_decision_version: Mapped[str | None] = mapped_column(Text(), nullable=True)
    #: What the proxy circuit breaker said at dispatch time (ALLOW /
    #: BLOCK / HALF_OPEN / ...), recorded as free text so the breaker can
    #: gain verdicts without a migration.
    breaker_decision: Mapped[str | None] = mapped_column(Text(), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime(), nullable=False, server_default=text("now()")
    )

    # --- immutable outcome, written exactly once at close -----------------
    #: Non-NULL means CLOSED. The trigger reads this column and nothing
    #: else to decide whether an UPDATE is allowed.
    closed_at: Mapped[datetime | None] = mapped_column(TZDateTime(), nullable=True)
    #: TRANSPORT-OBSERVED byte counts, the same fact as
    #: `request_attempts.main_document_bytes`/`subresource_bytes` (B6) and
    #: deliberately NOT provider-billed bytes — those are settlements.
    bytes_compressed: Mapped[int | None] = mapped_column(BigInteger(), nullable=True)
    bytes_decompressed: Mapped[int | None] = mapped_column(BigInteger(), nullable=True)
    response_status: Mapped[int | None] = mapped_column(Integer(), nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer(), nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(Text(), nullable=True)
    extraction_result: Mapped[str | None] = mapped_column(Text(), nullable=True)
    #: Categorical labels, mirroring
    #: `request_attempts.identity_validation_result` — deliberately not a
    #: numeric score, which would invite a float and imply a calibration
    #: nothing in this system actually produces.
    identity_confidence: Mapped[str | None] = mapped_column(Text(), nullable=True)
    comparability: Mapped[str | None] = mapped_column(Text(), nullable=True)
    #: The operation's cost as the FLEET estimated it at close, in
    #: currency minor units. Reconciled later, never overwritten (see
    #: `NetworkOperationSettlement`).
    estimated_cost_minor_units: Mapped[int | None] = mapped_column(
        BigInteger(), nullable=True
    )
    currency: Mapped[str | None] = mapped_column(String(length=3), nullable=True)
    #: What the provider bills BY (``GB``, ``REQUEST``, ``MINUTE``, ...)
    #: — the denominator `billing_rate_micro_units` is a rate over.
    billing_unit: Mapped[str | None] = mapped_column(Text(), nullable=True)
    billing_rate_micro_units: Mapped[int | None] = mapped_column(
        BigInteger(), nullable=True
    )
    rate_effective_date: Mapped[date | None] = mapped_column(Date(), nullable=True)


class NetworkOperationAllocation(Base, WorkspaceScopedBase):
    """``network_operation_allocations`` — the tenant-visible cost split.

    The ONLY RLS-protected table of the three (ENABLE + FORCE + the
    standard ``workspace_id = <ctx>`` policy, emitted in the creating
    migration). One row per (operation, workspace); a single-tenant
    operation gets exactly one row with ``fraction_ppb =
    FRACTION_SCALE``.

    ``allocated_cost_minor_units`` is computed with
    :func:`allocate_cost_largest_remainder`, and a DEFERRED constraint
    trigger re-checks at COMMIT that the rows for one operation sum
    exactly to that operation's ``estimated_cost_minor_units`` (and that
    the fractions sum to :data:`FRACTION_SCALE`). Deferred, not
    immediate, because an allocation set is written a row at a time and
    is only meaningful complete — an immediate check would reject the
    first correct row of every multi-tenant split.
    """

    __tablename__ = "network_operation_allocations"
    __table_args__ = (
        UniqueConstraint(
            "operation_id", "workspace_id", name="uq_noa_operation_id_workspace_id"
        ),
        ForeignKeyConstraint(
            ["operation_id"],
            ["network_operations.network_request_id"],
            name="fk_noa_operation_id_network_operations",
        ),
        ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_noa_workspace_id_workspaces",
        ),
        CheckConstraint(
            "fraction_ppb >= 0 AND fraction_ppb <= 1000000000",
            name="noa_fraction_in_range",
        ),
        CheckConstraint(
            "allocated_cost_minor_units >= 0",
            # Short suffix on purpose: the convention prefixes
            # `ck_network_operation_allocations_`, which already spends 33
            # of Postgres's 63 identifier bytes.
            name="noa_cost_non_negative",
        ),
        CheckConstraint("currency ~ '^[A-Z]{3}$'", name="noa_currency_is_iso4217"),
        Index("ix_noa_operation_id", "operation_id"),
    )

    operation_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), nullable=False)
    #: Exact scaled integer share, parts per billion (:data:`FRACTION_SCALE`
    #: == 1.0). Never a float, never a bare NUMERIC.
    fraction_ppb: Mapped[int] = mapped_column(BigInteger(), nullable=False)
    allocated_cost_minor_units: Mapped[int] = mapped_column(BigInteger(), nullable=False)
    currency: Mapped[str] = mapped_column(String(length=3), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime(), nullable=False, server_default=text("now()")
    )


class NetworkOperationSettlement(Base):
    """``network_operation_settlements`` — append-only reconciliation facts (C5).

    Written when the provider's own usage record arrives. A restatement
    APPENDS a higher ``settlement_version`` with ``method =
    CORRECTION``; the version it corrects is never touched. "Current
    reconciled cost" is therefore ``ORDER BY settlement_version DESC
    LIMIT 1``, not a mutable column — which is what makes the ledger
    auditable months later, when the only question that matters is what
    the system believed and when.

    Fleet-owned like the operation itself: no ``workspace_id``. A
    settlement restates the PHYSICAL cost; re-deriving each tenant's
    share of a corrected total is an allocation concern, not a
    settlement one.

    UPDATE and DELETE are both rejected by a trigger, so "append-only"
    is a property of the database rather than a property of whoever
    remembered.
    """

    __tablename__ = "network_operation_settlements"
    __table_args__ = (
        UniqueConstraint(
            "operation_id",
            "settlement_version",
            name="uq_nos_operation_id_settlement_version",
        ),
        ForeignKeyConstraint(
            ["operation_id"],
            ["network_operations.network_request_id"],
            name="fk_nos_operation_id_network_operations",
        ),
        CheckConstraint("settlement_version >= 1", name="nos_version_is_positive"),
        CheckConstraint(
            "reconciled_cost_minor_units >= 0", name="nos_cost_non_negative"
        ),
        CheckConstraint("currency ~ '^[A-Z]{3}$'", name="nos_currency_is_iso4217"),
        Index("ix_nos_operation_id", "operation_id"),
    )

    operation_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), nullable=False)
    settlement_version: Mapped[int] = mapped_column(Integer(), nullable=False)
    reconciled_cost_minor_units: Mapped[int] = mapped_column(BigInteger(), nullable=False)
    currency: Mapped[str] = mapped_column(String(length=3), nullable=False)
    #: The provider's own identifier for the usage record this
    #: settlement was derived from — the thread back to the invoice.
    provider_usage_record_id: Mapped[str | None] = mapped_column(Text(), nullable=True)
    method: Mapped[SettlementMethod] = enum_column(SettlementMethod, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime(), nullable=False, server_default=text("now()")
    )


# --- DDL emitted by the creating migration (C1) ---------------------------
#
# Kept HERE, next to the models whose invariants they enforce, for the
# same reason `app_shared.models.rls` keeps the RLS statements next to
# the mixin: a rule that lives only inside one migration file is a rule
# nobody reads again. None of these statements contains a `%` or a bare
# `:` — psycopg3 scans for placeholders whenever parameters are supplied,
# so `%`-formatted RAISE messages are unsafe to ship in text that may be
# executed with a parameter set (see `rls.PARTITION_RLS_INHERITANCE_SQL`).

#: Rejects (a) any UPDATE of a CLOSED operation row and (b) any UPDATE
#: that changes an intent column, open or closed. Together those two
#: rules mean the only legal UPDATE is the single close that fills in
#: the outcome fields.
NETWORK_OPERATION_IMMUTABILITY_SQL = """
CREATE OR REPLACE FUNCTION network_operations_reject_mutation()
RETURNS trigger AS $$
BEGIN
    IF OLD.closed_at IS NOT NULL THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'network_operations row is closed and immutable',
            DETAIL  = 'A closed physical operation is an append-only fact. '
                      'Record a correction as a new network_operation_settlements '
                      'version instead of rewriting history.';
    END IF;

    IF NEW.id                      IS DISTINCT FROM OLD.id
    OR NEW.network_request_id      IS DISTINCT FROM OLD.network_request_id
    OR NEW.created_at              IS DISTINCT FROM OLD.created_at
    OR NEW.retry_parent_id         IS DISTINCT FROM OLD.retry_parent_id
    OR NEW.parent_operation_id     IS DISTINCT FROM OLD.parent_operation_id
    OR NEW.scrape_job_id           IS DISTINCT FROM OLD.scrape_job_id
    OR NEW.canonical_url_hash      IS DISTINCT FROM OLD.canonical_url_hash
    OR NEW.domain                  IS DISTINCT FROM OLD.domain
    OR NEW.http_method             IS DISTINCT FROM OLD.http_method
    OR NEW.region                  IS DISTINCT FROM OLD.region
    OR NEW.provider                IS DISTINCT FROM OLD.provider
    OR NEW.provider_account        IS DISTINCT FROM OLD.provider_account
    OR NEW.transport               IS DISTINCT FROM OLD.transport
    OR NEW.authorization_id        IS DISTINCT FROM OLD.authorization_id
    OR NEW.entitlement_version     IS DISTINCT FROM OLD.entitlement_version
    OR NEW.budget_decision_version IS DISTINCT FROM OLD.budget_decision_version
    OR NEW.breaker_decision        IS DISTINCT FROM OLD.breaker_decision
    THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'network_operations intent fields are immutable',
            DETAIL  = 'Intent is written once at open. Only the outcome columns '
                      'may be filled in, and only by the single closing UPDATE.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_network_operations_immutable
BEFORE UPDATE ON network_operations
FOR EACH ROW EXECUTE FUNCTION network_operations_reject_mutation();
"""

#: Settlements never mutate: a correction appends a new version.
NETWORK_OPERATION_SETTLEMENTS_APPEND_ONLY_SQL = """
CREATE OR REPLACE FUNCTION network_operation_settlements_reject_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'network_operation_settlements is append-only',
        DETAIL  = 'UPDATE and DELETE are rejected. Append a new settlement_version '
                  'with method = CORRECTION; the latest version is the current '
                  'reconciled cost.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_network_operation_settlements_append_only
BEFORE UPDATE OR DELETE ON network_operation_settlements
FOR EACH ROW EXECUTE FUNCTION network_operation_settlements_reject_mutation();
"""

#: The DEFERRED total: at COMMIT, the allocations for one operation must
#: sum exactly to that operation's cost, and their fractions to 1.0.
#: Skipped while the operation has no cost yet (still open, or closed
#: with nothing to bill) and when the operation row is gone — there is
#: nothing to reconcile against in either case.
NETWORK_OPERATION_ALLOCATION_TOTAL_SQL = """
CREATE OR REPLACE FUNCTION network_operation_allocations_check_total()
RETURNS trigger AS $$
DECLARE
    op_id        uuid;
    op_cost      bigint;
    alloc_total  bigint;
    alloc_frac   bigint;
    alloc_count  integer;
BEGIN
    IF TG_OP = 'DELETE' THEN
        op_id := OLD.operation_id;
    ELSE
        op_id := NEW.operation_id;
    END IF;

    SELECT o.estimated_cost_minor_units
      INTO op_cost
      FROM network_operations o
     WHERE o.network_request_id = op_id;

    IF NOT FOUND OR op_cost IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT COALESCE(SUM(a.allocated_cost_minor_units), 0),
           COALESCE(SUM(a.fraction_ppb), 0),
           COUNT(*)
      INTO alloc_total, alloc_frac, alloc_count
      FROM network_operation_allocations a
     WHERE a.operation_id = op_id;

    IF alloc_count = 0 THEN
        RETURN NULL;
    END IF;

    IF alloc_total <> op_cost THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'network_operation_allocations do not sum to the operation cost',
            DETAIL  = 'allocated total ' || alloc_total::text
                      || ' minor units vs operation cost ' || op_cost::text
                      || ' minor units. Split with largest-remainder rounding so the '
                      || 'parts sum exactly.';
    END IF;

    IF alloc_frac <> 1000000000 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'network_operation_allocations fractions do not sum to 1.0',
            DETAIL  = 'fraction_ppb total ' || alloc_frac::text || ' of 1000000000.';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_noa_allocation_total
AFTER INSERT OR UPDATE OR DELETE ON network_operation_allocations
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION network_operation_allocations_check_total();
"""

#: Dropped by the migration's downgrade, in dependency order.
NETWORK_OPERATION_LEDGER_DROP_SQL = """
DROP TRIGGER IF EXISTS trg_noa_allocation_total ON network_operation_allocations;
DROP FUNCTION IF EXISTS network_operation_allocations_check_total();
DROP TRIGGER IF EXISTS trg_network_operation_settlements_append_only
    ON network_operation_settlements;
DROP FUNCTION IF EXISTS network_operation_settlements_reject_mutation();
DROP TRIGGER IF EXISTS trg_network_operations_immutable ON network_operations;
DROP FUNCTION IF EXISTS network_operations_reject_mutation();
"""
