"""smoke_foundation

Revision ID: 023a24e5717d
Revises:
Create Date: 2026-07-02 00:00:00.000000

First (head) migration for SPEC-02 US1 (contracts/migration-job.md,
data-model.md "Entity: Demonstration / smoke table"). Creates the
tiny, permanent, NON-domain ``_smoke_foundation`` table that proves the
shared machinery end-to-end in one place:

* a UUIDv7 primary key (``id``, application-generated — see
  ``app_shared.ids.new_uuid7`` / ``app_shared.models.base.Base``);
* ``TIMESTAMPTZ`` timestamp columns (``created_at``/``updated_at`` via
  ``app_shared.models.base.TimestampMixin``);
* a ``NUMERIC(18, 4)`` money column (``amount``, via
  ``app_shared.money.Money``);
* a string-backed, app-validated enum column (``status``, via
  ``app_shared.enums.enum_column`` / ``RecordStatus``);
* two multi-column ``UNIQUE`` constraints sharing the leading
  ``group_key`` column, which the naming convention's
  ``column_0_N_name`` token renders under two DISTINCT names instead of
  colliding (FR-002, SC-003):
  ``uq__smoke_foundation_group_key_code_a`` and
  ``uq__smoke_foundation_group_key_code_b``.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment — Alembic autogenerate
needs a real DB connection to diff against. The column/constraint
shapes below are reproduced exactly from
``app_shared.models._smoke.SmokeFoundation`` and its declared naming
convention (verified via the offline ``--sql`` render in
``tests/unit/test_migration_offline.py``).

This table is deliberately **not** workspace-owned (no
``workspace_id``, no RLS) — it is non-domain test/demo support, not a
real isolation surface. A *future* migration creating a real
workspace-owned table (first one arrives in SPEC-03) would, in this
same migration, additionally call::

    from app_shared.models import emit_rls_policy

    for statement in emit_rls_policy("some_workspace_owned_table"):
        op.execute(statement)

right after ``op.create_table(...)`` for that table — enabling
fail-closed row-level security in the same migration that creates the
table (§32). Not applied here since ``_smoke_foundation`` has no
``workspace_id`` column.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "023a24e5717d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create the ``_smoke_foundation`` demo table."""
    op.create_table(
        "_smoke_foundation",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("group_key", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("code_a", sa.Text(), nullable=True),
        sa.Column("code_b", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk__smoke_foundation"),
        sa.UniqueConstraint(
            "group_key", "code_a", name="uq__smoke_foundation_group_key_code_a"
        ),
        sa.UniqueConstraint(
            "group_key", "code_b", name="uq__smoke_foundation_group_key_code_b"
        ),
    )


def downgrade() -> None:
    """Downgrade schema: drop the ``_smoke_foundation`` demo table (FR-016)."""
    op.drop_table("_smoke_foundation")
