"""webhook_events_and_endpoints

Revision ID: 03dec3037c8f
Revises: 4a1dca402f78
Create Date: 2026-07-06 00:00:00.000000

The two SPEC-16 tables (data-model.md / contracts/rest-api.md /
contracts/events.md): ``webhook_endpoints`` (plain, not partitioned —
mirrors the SPEC-13 ``refresh_rules`` precedent) and ``webhook_events``
(**monthly-partitioned by ``created_at`` from birth**, mirroring the
SPEC-09 ``price_alert_events`` precedent, research R3, Constitution
§22/§29). Both are workspace-owned — RLS is enabled in this SAME
migration for both (FR-016/FR-017, §32, Principle II), matching the
SPEC-04..15 precedent.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.webhooks`` exactly. The
partitioned parent declares ``postgresql_partition_by`` (rendering
``PARTITION BY RANGE (...)``) with a composite primary key that
includes the partition column (Postgres's rule for partitioned
tables); current + next month ``PARTITION OF`` children are created
via raw ``op.execute`` (no ``op.create_table`` support for partition
children) using the same ``_month_partition_bounds`` helper copied
verbatim from ``e4a75b48360c_alerts_price_states_tables.py``. RLS
applied to a partitioned **parent** propagates to its partitions, so
it is only emitted once per parent, not per partition. ``event_type``/
``payload`` carry **no** FK (soft/deferred references, §22); only
``workspace_id`` gets a real FK (the RLS anchor) on either table.

Does NOT touch ``PARTITIONED_TABLES``
(``app_shared/maintenance/registry.py``) — ``webhook_events`` is
already registered there; this migration only creates the real table
so the existing ``table_exists`` gate activates the already-registered
partition-create/retention jobs.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = '03dec3037c8f'
down_revision: Union[str, Sequence[str], None] = '4a1dca402f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _month_partition_bounds(base: datetime) -> list[tuple[str, str, str]]:
    """Return ``[(suffix, start_date, end_date_exclusive), ...]`` for
    ``base``'s month and the following month (current + next), each as
    ``YYYY-MM-01`` ISO date strings. ``suffix`` is ``YYYY_MM`` (< 63-byte
    partition table name budget once prefixed with ``webhook_events_``).
    Copied verbatim from ``e4a75b48360c_alerts_price_states_tables.py``.
    """
    bounds: list[tuple[str, str, str]] = []
    year, month = base.year, base.month
    for offset in range(2):
        m = month + offset
        y = year
        if m > 12:
            m -= 12
            y += 1
        start = f"{y:04d}-{m:02d}-01"
        next_m = m + 1
        next_y = y
        if next_m > 12:
            next_m = 1
            next_y += 1
        end = f"{next_y:04d}-{next_m:02d}-01"
        bounds.append((f"{y:04d}_{m:02d}", start, end))
    return bounds


def upgrade() -> None:
    """Upgrade schema: create webhook_endpoints (plain), the partitioned
    webhook_events parent + initial partitions, and RLS
    (ENABLE+FORCE+fail-closed) on both."""
    now = datetime.now(timezone.utc)

    # --- webhook_endpoints (plain, NOT partitioned) --------------------------
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=True),
        sa.Column("secret_key_version", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("event_types", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_endpoints"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_webhook_endpoints_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_webhook_endpoints_workspace_id", "webhook_endpoints", ["workspace_id"]
    )

    # --- webhook_events (PARTITIONED by created_at) --------------------------
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at", name="pk_webhook_events"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_webhook_events_workspace_id_workspaces",
        ),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "ix_webhook_events_workspace_id", "webhook_events", ["workspace_id"]
    )
    op.create_index(
        "ix_webhook_events_ws_created_id",
        "webhook_events",
        ["workspace_id", "created_at", "id"],
    )
    op.create_index(
        "ix_webhook_events_ws_type_created",
        "webhook_events",
        ["workspace_id", "event_type", "created_at"],
    )

    for suffix, start, end in _month_partition_bounds(now):
        op.execute(
            f"CREATE TABLE webhook_events_{suffix} PARTITION OF webhook_events "
            f"FOR VALUES FROM ('{start}') TO ('{end}');"
        )

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-016/FR-017, §32, Principle II) — both. Applying RLS to a
    # partitioned parent propagates to its partitions (current +
    # future), so this is emitted once per parent, not per partition.
    for table in ("webhook_endpoints", "webhook_events"):
        for statement in emit_rls_policy(table):
            op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop each webhook_events partition + parent,
    then webhook_endpoints (reverse of creation order)."""
    now = datetime.now(timezone.utc)

    for suffix, _start, _end in _month_partition_bounds(now):
        op.execute(f"DROP TABLE IF EXISTS webhook_events_{suffix};")
    op.drop_table("webhook_events")

    op.drop_table("webhook_endpoints")
