"""observations_current_prices_tables

Revision ID: 2db33dea5e14
Revises: a4f205e8d7de
Create Date: 2026-07-03 00:00:00.000000

The three SPEC-07 tables (contracts/migration-observations.md,
data-model.md): ``price_observations``, ``request_attempts`` (both
**monthly-partitioned from birth** — the first partitioned tables in the
repo, research D3, Constitution §22/§29) and ``match_current_prices``
(current-state, not partitioned). All three are workspace-owned — RLS is
enabled in this SAME migration for all three (FR-012, §32, Principle
II), matching the SPEC-04/05/06 precedent.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.observations`` exactly. The two
partitioned parents declare ``postgresql_partition_by`` (rendering
``PARTITION BY RANGE (...)``) with a composite primary key that
includes the partition column (Postgres's rule for partitioned
tables); current + next month ``PARTITION OF`` children are created via
raw ``op.execute`` (no ``op.create_table`` support for partition
children). RLS applied to a partitioned **parent** propagates to its
partitions, so it is only emitted once per parent, not per partition.
``match_id``/``product_id``/``product_variant_id``/``competitor_id``/
``scrape_job_id``/``observation_id`` all carry **no** FK (soft/deferred
references — retention-by-drop tolerance, §22); only ``workspace_id``
gets a real FK (the RLS anchor).
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = '2db33dea5e14'
down_revision: Union[str, Sequence[str], None] = 'a4f205e8d7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _month_partition_bounds(base: datetime) -> list[tuple[str, str, str]]:
    """Return ``[(suffix, start_date, end_date_exclusive), ...]`` for
    ``base``'s month and the following month (current + next, per
    contracts/migration-observations.md), each as ``YYYY-MM-01`` ISO
    date strings. ``suffix`` is ``YYYY_MM`` (< 63-byte partition table
    name budget once prefixed with ``price_observations_``/
    ``request_attempts_``).
    """
    bounds: list[tuple[str, str, str]] = []
    year, month = base.year, base.month
    for offset in range(2):
        m = month + offset
        y = year
        if m > 12:
            m -= 12
            y += 1
        start = f"{y:04d}-{m:02d}-01"
        next_m = m + 1
        next_y = y
        if next_m > 12:
            next_m = 1
            next_y += 1
        end = f"{next_y:04d}-{next_m:02d}-01"
        bounds.append((f"{y:04d}_{m:02d}", start, end))
    return bounds


def upgrade() -> None:
    """Upgrade schema: create the two partitioned parents + initial partitions,
    the match_current_prices table, and RLS (ENABLE+FORCE+fail-closed) on all three."""
    now = datetime.now(timezone.utc)

    # --- price_observations (PARTITIONED by scraped_at) --------------------
    op.create_table(
        "price_observations",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("match_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("old_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=True),
        sa.Column("stock_status", sa.String(length=32), nullable=True),
        sa.Column("raw_title", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("comparable", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extraction_method", sa.String(length=32), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("selector_used", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", "scraped_at", name="pk_price_observations"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_price_observations_workspace_id_workspaces",
        ),
        postgresql_partition_by="RANGE (scraped_at)",
    )
    op.create_index(
        "ix_price_observations_workspace_id", "price_observations", ["workspace_id"]
    )
    op.create_index("ix_price_observations_match_id", "price_observations", ["match_id"])

    for suffix, start, end in _month_partition_bounds(now):
        op.execute(
            f"CREATE TABLE price_observations_{suffix} PARTITION OF price_observations "
            f"FOR VALUES FROM ('{start}') TO ('{end}');"
        )

    # --- request_attempts (PARTITIONED by created_at) -----------------------
    op.create_table(
        "request_attempts",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("match_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("access_method", sa.String(length=32), nullable=False),
        sa.Column("proxy_provider_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("proxy_country", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at", name="pk_request_attempts"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_request_attempts_workspace_id_workspaces",
        ),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index("ix_request_attempts_workspace_id", "request_attempts", ["workspace_id"])
    op.create_index("ix_request_attempts_match_id", "request_attempts", ["match_id"])

    for suffix, start, end in _month_partition_bounds(now):
        op.execute(
            f"CREATE TABLE request_attempts_{suffix} PARTITION OF request_attempts "
            f"FOR VALUES FROM ('{start}') TO ('{end}');"
        )

    # --- match_current_prices (current-state, NOT partitioned) --------------
    op.create_table(
        "match_current_prices",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("match_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("old_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=True),
        sa.Column("stock_status", sa.String(length=32), nullable=True),
        sa.Column("comparable", sa.Boolean(), nullable=False),
        sa.Column("observation_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("extraction_method", sa.String(length=32), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_match_current_prices"),
        sa.UniqueConstraint(
            "workspace_id",
            "match_id",
            name="uq_match_current_prices_workspace_id_match_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_match_current_prices_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_match_current_prices_workspace_id", "match_current_prices", ["workspace_id"]
    )

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-012, §32, Principle II) — all three. Applying RLS to a
    # partitioned parent propagates to its partitions (current +
    # future), so this is emitted once per parent, not per partition.
    for statement in emit_rls_policy("price_observations"):
        op.execute(statement)
    for statement in emit_rls_policy("request_attempts"):
        op.execute(statement)
    for statement in emit_rls_policy("match_current_prices"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop match_current_prices, then each partitioned
    table's partitions + parent (reverse of creation order)."""
    now = datetime.now(timezone.utc)

    op.drop_table("match_current_prices")

    for suffix, _start, _end in _month_partition_bounds(now):
        op.execute(f"DROP TABLE IF EXISTS request_attempts_{suffix};")
    op.drop_table("request_attempts")

    for suffix, _start, _end in _month_partition_bounds(now):
        op.execute(f"DROP TABLE IF EXISTS price_observations_{suffix};")
    op.drop_table("price_observations")
