"""variant_price_daily_rollups

Revision ID: 4a1dca402f78
Revises: 93511d5f7885
Create Date: 2026-07-06 00:00:00.000000

The single SPEC-15 US2 table (data-model.md §1, contracts/daily-rollup.md,
research R1/R5): `variant_price_daily_rollups`. Workspace-owned — RLS is
enabled in this SAME migration (FR-009a, §32, Principle II), matching the
SPEC-04/05/06/07/08/09/10/12/13 precedent.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint shapes
reproduce ``app_shared.models.rollups.VariantPriceDailyRollup`` exactly:

* Single-column UUIDv7 ``id`` PK (not partitioned, research R5).
* ``UniqueConstraint(workspace_id, product_variant_id, date)`` — the
  upsert conflict arbiter (FR-010). Named ``uq_vpdr_workspace_id_
  product_variant_id_date`` (the naming-convention-expanded form exceeds
  Postgres's 63-byte identifier cap) — the same explicit-shorthand
  precedent as ``dsp``/``sas``/``sdr``/``rr``/``cpm`` elsewhere in the repo.
* A real FK on ``workspace_id`` only (the RLS anchor); ``product_id``/
  ``product_variant_id`` are soft references (no FK), matching §22.
* ``client_price`` NOT NULL; ``cheapest_/average_/highest_competitor_price``
  nullable (NULL when ``comparable_competitor_count = 0``, FR-013) — all
  four as ``NUMERIC(18, 4)`` (``Money``, FR-012).
* Two indexes: ``workspace_id`` (mirrors the auto ``WorkspaceScopedBase``
  index every other workspace-owned table gets) and ``date`` (supports
  the US3 retention/coverage ``WHERE date >= d0 AND date < dN`` range
  scan, research R7).

``downgrade()`` drops both indexes then the table (RLS/policy drop with
the table). This is the single migration this feature adds — partition
create/drop DDL is runtime job logic (research R2), never a migration.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = '4a1dca402f78'
down_revision: Union[str, Sequence[str], None] = '93511d5f7885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create variant_price_daily_rollups + RLS."""
    op.create_table(
        "variant_price_daily_rollups",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("client_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cheapest_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("average_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("highest_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("comparable_competitor_count", sa.Integer(), nullable=False),
        sa.Column("latest_alert_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_variant_price_daily_rollups"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_variant_price_daily_rollups_workspace_id_workspaces",
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "product_variant_id",
            "date",
            name="uq_vpdr_workspace_id_product_variant_id_date",
        ),
    )
    op.create_index(
        "ix_variant_price_daily_rollups_workspace_id",
        "variant_price_daily_rollups",
        ["workspace_id"],
    )
    op.create_index(
        "ix_variant_price_daily_rollups_date",
        "variant_price_daily_rollups",
        ["date"],
    )

    # RLS in the SAME migration that creates the workspace-owned table
    # (FR-009a, §32, Principle II).
    for statement in emit_rls_policy("variant_price_daily_rollups"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop both indexes then the table."""
    op.drop_index("ix_variant_price_daily_rollups_date", table_name="variant_price_daily_rollups")
    op.drop_index(
        "ix_variant_price_daily_rollups_workspace_id", table_name="variant_price_daily_rollups"
    )
    op.drop_table("variant_price_daily_rollups")
