"""auth_identity_tables

Revision ID: 55da7d6d939d
Revises: 023a24e5717d
Create Date: 2026-07-02 21:20:02.655865

First real, workspace-owned application tables (SPEC-03 T012,
contracts/migration-identity.md, data-model.md). Creates the four
identity tables and enables fail-closed row-level security on the two
workspace-owned ones in the SAME migration (FR-004, §32, Principle II):

* ``workspaces`` — tenant root, NO RLS.
* ``users`` — workspace-owned, RLS. ``workspace_id`` is NULLABLE (a
  cross-workspace SUPER_ADMIN has no home workspace) — the nullable
  column interacts with the RLS predicate correctly and by design:
  ``NULL = x`` is never true, so a NULL-workspace row never matches any
  workspace context (fail-closed).
* ``refresh_tokens`` — user-owned, NO RLS (reached only by an
  unforgeable ``token_hash``, never enumerated/filtered by workspace).
* ``api_keys`` — workspace-owned, RLS. ``workspace_id`` is NOT NULL.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.identity`` exactly, honoring the
SPEC-02 ``NAMING_CONVENTION``.

Two-role note (research D4): RLS FORCE applies to the table owner too.
The request-serving role (``crawmatic_app``, ``DATABASE_URL``) has NO
BYPASSRLS. A dedicated ``crawmatic_auth`` role with BYPASSRLS (via
``AUTH_DATABASE_URL``) performs only the pre-context credential lookups
(user-by-email, api-key-by-prefix). Creating these DB roles is a
cluster-level ops step (documented in quickstart.md), not part of this
migration's DDL — roles are not schema objects Alembic manages here.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = '55da7d6d939d'
down_revision: Union[str, Sequence[str], None] = '023a24e5717d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create the four identity tables + RLS on users/api_keys."""
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("default_scrape_profile_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("default_access_policy_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workspaces"),
        sa.UniqueConstraint("slug", name="uq_workspaces_slug"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_users_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_users_workspace_id", "users", ["workspace_id"])

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_refresh_tokens_user_id_users",
        ),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index(
        "ix_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"]
    )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_api_keys"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_api_keys_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_api_keys_workspace_id", "api_keys", ["workspace_id"])
    op.create_index("ix_api_keys_key_prefix", "api_keys", ["key_prefix"])

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-004, §32, Principle II). `workspaces` (tenant root) and
    # `refresh_tokens` (user-owned, reached only by unforgeable
    # token_hash) get NO RLS — see data-model.md "Isolation & RLS
    # summary".
    for statement in emit_rls_policy("users"):
        op.execute(statement)
    for statement in emit_rls_policy("api_keys"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the four identity tables in FK-safe order."""
    op.drop_table("api_keys")
    op.drop_table("refresh_tokens")
    op.drop_table("users")
    op.drop_table("workspaces")
