"""access_policies_proxies_tables

Revision ID: 851220acab90
Revises: e4a75b48360c
Create Date: 2026-07-04 00:00:00.000000

The three SPEC-10 tables (contracts/migration-access.md, data-model.md):
``proxy_providers`` + ``access_policies`` — **dual-scope** (``workspace_id``
nullable; ``NULL`` = a global/shared default, mirroring the SPEC-06
``scrape_profiles`` pattern, research D2) — and ``domain_access_rules``
— **tenant-only** (``workspace_id NOT NULL``, standard RLS). RLS is
enabled in this SAME migration: ``emit_global_readable_rls_policy`` for
the two dual-scope tables (read own+global, write own-only, FR-006) and
the standard ``emit_rls_policy`` for ``domain_access_rules``, matching
the SPEC-04..09 precedent of emitting RLS alongside table creation.

Soft references (``provider_id``, ``access_policy_id``, ``competitor_id``)
carry **no** FK (§22 soft-reference philosophy — tolerate a disabled/
deleted referent; readers must degrade gracefully); only ``workspace_id``
gets a real FK (the RLS anchor).

``request_attempts`` is **NOT** touched here — it already exists
(SPEC-07, ``2db33dea5e14``). No ``op.add_column``, no new table for it
(research D1).

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.access`` exactly.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_global_readable_rls_policy, emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = '851220acab90'
down_revision: Union[str, Sequence[str], None] = 'e4a75b48360c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create the 3 access/proxy tables + RLS on all three."""

    # --- proxy_providers (DUAL-SCOPE) ----------------------------------
    op.create_table(
        "proxy_providers",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("password_encrypted", sa.Text(), nullable=True),
        sa.Column("password_key_version", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("monthly_budget_limit", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_proxy_providers"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_proxy_providers_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_proxy_providers_workspace_id", "proxy_providers", ["workspace_id"])
    op.create_index(
        "uq_proxy_providers_workspace_id_name",
        "proxy_providers",
        ["workspace_id", "name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.create_index(
        "uq_proxy_providers_name_global",
        "proxy_providers",
        ["name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )

    # --- access_policies (DUAL-SCOPE) ----------------------------------
    op.create_table(
        "access_policies",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("use_proxy_on_first_attempt", sa.Boolean(), nullable=False),
        sa.Column("use_proxy_on_retry", sa.Boolean(), nullable=False),
        sa.Column("allow_browser_fallback", sa.Boolean(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("rotate_per_request", sa.Boolean(), nullable=False),
        sa.Column("sticky_session", sa.Boolean(), nullable=False),
        sa.Column("session_ttl_minutes", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_minute", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_hour", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_day", sa.Integer(), nullable=True),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_access_policies"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_access_policies_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_access_policies_workspace_id", "access_policies", ["workspace_id"])
    op.create_index(
        "uq_access_policies_workspace_id_name",
        "access_policies",
        ["workspace_id", "name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.create_index(
        "uq_access_policies_name_global",
        "access_policies",
        ["name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )

    # --- domain_access_rules (TENANT-ONLY) -----------------------------
    op.create_table(
        "domain_access_rules",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("url_pattern", sa.Text(), nullable=True),
        sa.Column("url_pattern_override", sa.Text(), nullable=True),
        sa.Column("access_policy_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("max_concurrent_requests", sa.Integer(), nullable=False),
        sa.Column("max_requests_per_minute", sa.Integer(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "block_detection_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_domain_access_rules"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_domain_access_rules_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_domain_access_rules_workspace_id", "domain_access_rules", ["workspace_id"]
    )
    op.create_index(
        "ix_domain_access_rules_workspace_id_competitor_id_domain",
        "domain_access_rules",
        ["workspace_id", "competitor_id", "domain"],
    )
    op.create_index(
        "uq_domain_access_rules_ws_cid_domain_pattern",
        "domain_access_rules",
        ["workspace_id", "competitor_id", "domain", sa.text("COALESCE(url_pattern, '')")],
        unique=True,
    )

    # RLS in the SAME migration that creates the tables (§32, Principle II):
    # dual-scope (own+global read, own-only write) for the two dual-scope
    # tables; standard fail-closed isolation for domain_access_rules.
    for statement in emit_global_readable_rls_policy("proxy_providers"):
        op.execute(statement)
    for statement in emit_global_readable_rls_policy("access_policies"):
        op.execute(statement)
    for statement in emit_rls_policy("domain_access_rules"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the 3 tables in reverse creation order."""
    op.drop_table("domain_access_rules")
    op.drop_table("access_policies")
    op.drop_table("proxy_providers")
