"""refresh_rules

Revision ID: 93511d5f7885
Revises: f30c60cfa2f7
Create Date: 2026-07-05 00:00:00.000000

The single SPEC-13 US1 table (data-model.md): ``refresh_rules``. Workspace-owned
— RLS is enabled in this SAME migration (FR-005, §32, Principle II), matching
the SPEC-04/05/06/07/08/09/10/12 precedent.

Hand-authored (not autogenerated) because there is no live Postgres connection
available in this build environment. Column/constraint shapes reproduce
``app_shared.models.refresh_rules.RefreshRule`` exactly:

* Five nullable, workspace-local **composite** scope-target FKs
  (``(workspace_id, X) -> table(workspace_id, id)``), each ``ondelete="CASCADE"``
  (research R7) — deleting a product/variant/group/competitor/match cascades
  away the rules that target it, so the scheduler pass never dereferences a
  missing target.
* Three CHECK constraints (research R9): exactly-one-cadence
  (``num_nonnulls(cron_expression, interval_minutes) = 1``), positive interval,
  and the scope<->target-id matrix (``ck_refresh_rules_scope_target``).
* The partial due-claim index ``ix_refresh_rules_due`` on ``(next_run_at)
  WHERE enabled`` (research R5, Principle VIII) — supports
  ``WHERE enabled AND next_run_at <= now() ORDER BY next_run_at`` cheaply.

``downgrade()`` drops the partial index then the table (RLS/policy drop with
the table).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = '93511d5f7885'
down_revision: Union[str, Sequence[str], None] = 'f30c60cfa2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_SCOPE_TARGET_CHECK = (
    "("
    "scope = 'WORKSPACE' AND product_id IS NULL AND product_variant_id IS NULL "
    "AND product_group_id IS NULL AND competitor_id IS NULL AND match_id IS NULL"
    ") OR ("
    "scope = 'COMPETITOR' AND competitor_id IS NOT NULL AND product_id IS NULL "
    "AND product_variant_id IS NULL AND product_group_id IS NULL AND match_id IS NULL"
    ") OR ("
    "scope = 'PRODUCT' AND product_id IS NOT NULL AND product_variant_id IS NULL "
    "AND product_group_id IS NULL AND competitor_id IS NULL AND match_id IS NULL"
    ") OR ("
    "scope = 'VARIANT' AND product_variant_id IS NOT NULL AND product_id IS NULL "
    "AND product_group_id IS NULL AND competitor_id IS NULL AND match_id IS NULL"
    ") OR ("
    "scope = 'PRODUCT_GROUP' AND product_group_id IS NOT NULL AND product_id IS NULL "
    "AND product_variant_id IS NULL AND competitor_id IS NULL AND match_id IS NULL"
    ") OR ("
    "scope = 'MATCH' AND match_id IS NOT NULL AND product_id IS NULL "
    "AND product_variant_id IS NULL AND product_group_id IS NULL AND competitor_id IS NULL"
    ")"
)


def upgrade() -> None:
    """Upgrade schema: create refresh_rules + RLS."""
    op.create_table(
        "refresh_rules",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("product_group_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("match_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("cron_expression", sa.Text(), nullable=True),
        sa.Column("interval_minutes", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_rules"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_refresh_rules_workspace_id_workspaces",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_rr_workspace_product_products",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_variant_id"],
            ["product_variants.workspace_id", "product_variants.id"],
            name="fk_rr_workspace_variant_variants",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_group_id"],
            ["product_groups.workspace_id", "product_groups.id"],
            name="fk_rr_workspace_group_groups",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "competitor_id"],
            ["competitors.workspace_id", "competitors.id"],
            name="fk_rr_workspace_competitor_competitors",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "match_id"],
            ["competitor_product_matches.workspace_id", "competitor_product_matches.id"],
            name="fk_rr_workspace_match_matches",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "num_nonnulls(cron_expression, interval_minutes) = 1",
            name="ck_refresh_rules_exactly_one_cadence",
        ),
        sa.CheckConstraint(
            "interval_minutes IS NULL OR interval_minutes > 0",
            name="ck_refresh_rules_interval_minutes_positive",
        ),
        sa.CheckConstraint(
            _SCOPE_TARGET_CHECK,
            name="ck_refresh_rules_scope_target",
        ),
    )
    op.create_index("ix_refresh_rules_workspace_id", "refresh_rules", ["workspace_id"])
    op.create_index(
        "ix_refresh_rules_due",
        "refresh_rules",
        ["next_run_at"],
        postgresql_where=sa.text("enabled"),
    )

    # RLS in the SAME migration that creates the workspace-owned table
    # (FR-005, §32, Principle II).
    for statement in emit_rls_policy("refresh_rules"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the partial index then the table."""
    op.drop_index("ix_refresh_rules_due", table_name="refresh_rules")
    op.drop_table("refresh_rules")
