"""scrape_profiles: regex execution quarantine columns (A2/F02)

Revision ID: a2f0217c9d43
Revises: c8d2e3f4a5b6
Create Date: 2026-09-07

EPA A2 (F02, "Regex execution with a hard timeout"). Two columns on
``scrape_profiles``, the table that actually stores the customer-supplied
``price_regex``/``old_price_regex``/``currency_regex``/``stock_regex``
patterns:

* ``regex_timeout_count INT NOT NULL DEFAULT 0`` — how many times this
  profile's regex rules have blown their live execution deadline
  (``ScrapeErrorCode.REGEX_TIMEOUT``).
* ``regex_quarantined_at TIMESTAMPTZ NULL`` — stamped once that counter
  reaches ``EXTRACTION_REGEX_QUARANTINE_AFTER``. While it is non-NULL the
  extraction chain skips this profile's regex strategy entirely; the page
  still gets its other four readings. Cleared by
  ``POST /admin/profiles/{id}/regex-unquarantine``.

Naming note
-----------
The plan text calls the table ``strategy_profiles``. No such table
exists. The two candidates are ``scrape_profiles`` (which owns every
``*_regex`` column and is what the preflight script enumerates) and
``domain_strategy_profiles`` (the learned per-domain access/extraction
start, which carries no regex at all). The quarantine is about a stored
pattern, so it belongs on the row that stores the pattern:
``scrape_profiles``.

Why ``regex_quarantined_at`` is NULLABLE and the counter is NOT NULL
--------------------------------------------------------------------
``NULL`` on the timestamp is the only honest encoding of "never
quarantined" — a sentinel date would be indistinguishable from a real,
very old quarantine and every reader would have to know the sentinel.
The counter is the opposite case: ``0`` is a true, complete statement
about every existing row (none of them have timed out, because the code
that could record a timeout ships with this migration), so NOT NULL
DEFAULT 0 introduces no ambiguity and spares every reader a COALESCE.

Hand-authored (not autogenerated): there is no live Postgres connection
in this build environment. Shapes reproduce
``app_shared.models.scrape_profiles.ScrapeProfile`` exactly.

No GRANT block: both columns are added to an existing table, and
``crawmatic_app``'s table-level privileges on ``scrape_profiles`` already
cover every column it will ever have (PostgreSQL table grants are not
per-column unless column privileges were granted explicitly, and they
were not).

``downgrade()`` drops both columns.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2f0217c9d43'
down_revision: Union[str, Sequence[str], None] = 'c8d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: add the two regex-quarantine columns."""
    op.add_column(
        "scrape_profiles",
        sa.Column(
            "regex_timeout_count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "scrape_profiles",
        sa.Column(
            "regex_quarantined_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema: drop the two regex-quarantine columns."""
    op.drop_column("scrape_profiles", "regex_quarantined_at")
    op.drop_column("scrape_profiles", "regex_timeout_count")
