"""scrape_profiles_table

Revision ID: a4f205e8d7de
Revises: f4c8a391d5c9
Create Date: 2026-07-03 11:54:10.745265

The one SPEC-06 table (contracts/migration-scrape-profiles.md,
data-model.md): ``scrape_profiles`` — the project's first **dual-scope**
table (``workspace_id`` nullable; ``NULL`` = a global/shared default,
research D2). RLS is enabled in this SAME migration via the custom
:func:`app_shared.models.rls.emit_global_readable_rls_policy` (read
own+global, write own-only, FR-021), matching the SPEC-04/05 precedent
of emitting RLS alongside table creation.

This migration also promotes three **existing** nullable columns
(created by SPEC-03/SPEC-05) to plain FKs -> ``scrape_profiles(id)``
``ON DELETE SET NULL`` (research D5, FR-012/FR-023):
``workspaces.default_scrape_profile_id``,
``competitors.default_scrape_profile_id``,
``competitor_product_matches.scrape_profile_id``. Plain (not composite)
because a global (``workspace_id IS NULL``) profile must be assignable
by any workspace — a workspace-local composite FK would forbid that.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.scrape_profiles`` exactly. No
global-profile seeding here (research D11 — out-of-band privileged/
BYPASSRLS path).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_global_readable_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'a4f205e8d7de'
down_revision: Union[str, Sequence[str], None] = 'f4c8a391d5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create scrape_profiles + RLS + promote 3 assignment FKs."""
    op.create_table(
        "scrape_profiles",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("adapter_key", sa.String(length=32), nullable=False),
        sa.Column("jsonld_enabled", sa.Boolean(), nullable=False),
        sa.Column("platform_patterns_enabled", sa.Boolean(), nullable=False),
        sa.Column("embedded_json_enabled", sa.Boolean(), nullable=False),
        sa.Column("price_selector", sa.Text(), nullable=True),
        sa.Column("price_xpath", sa.Text(), nullable=True),
        sa.Column("price_regex", sa.Text(), nullable=True),
        sa.Column("old_price_selector", sa.Text(), nullable=True),
        sa.Column("old_price_xpath", sa.Text(), nullable=True),
        sa.Column("old_price_regex", sa.Text(), nullable=True),
        sa.Column("currency_selector", sa.Text(), nullable=True),
        sa.Column("currency_xpath", sa.Text(), nullable=True),
        sa.Column("currency_regex", sa.Text(), nullable=True),
        sa.Column("stock_selector", sa.Text(), nullable=True),
        sa.Column("stock_xpath", sa.Text(), nullable=True),
        sa.Column("stock_regex", sa.Text(), nullable=True),
        sa.Column("title_selector", sa.Text(), nullable=True),
        sa.Column("title_xpath", sa.Text(), nullable=True),
        sa.Column("variant_strategy", sa.String(length=32), nullable=False),
        sa.Column(
            "variant_selector_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "price_transform_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("validation_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("wait_for_selector", sa.Text(), nullable=True),
        sa.Column("request_timeout_ms", sa.Integer(), nullable=False),
        sa.Column("browser_timeout_ms", sa.Integer(), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cookies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scrape_profiles"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_scrape_profiles_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_scrape_profiles_workspace_id", "scrape_profiles", ["workspace_id"])
    op.create_index(
        "uq_scrape_profiles_workspace_id_name",
        "scrape_profiles",
        ["workspace_id", "name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.create_index(
        "uq_scrape_profiles_name_global",
        "scrape_profiles",
        ["name"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )

    # Custom global-readable RLS in the SAME migration that creates the
    # table (FR-021, §32): read own+global, write own-only.
    for statement in emit_global_readable_rls_policy("scrape_profiles"):
        op.execute(statement)

    # Promote the three existing nullable assignment columns to plain FKs
    # -> scrape_profiles(id) ON DELETE SET NULL (research D5, FR-012/023).
    op.create_foreign_key(
        "fk_competitors_default_scrape_profile_id_scrape_profiles",
        "competitors",
        "scrape_profiles",
        ["default_scrape_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_cpm_scrape_profile_id_scrape_profiles",
        "competitor_product_matches",
        "scrape_profiles",
        ["scrape_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_workspaces_default_scrape_profile_id_scrape_profiles",
        "workspaces",
        "scrape_profiles",
        ["default_scrape_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    """Downgrade schema: drop the 3 promoted FKs, then the scrape_profiles table."""
    op.drop_constraint(
        "fk_workspaces_default_scrape_profile_id_scrape_profiles",
        "workspaces",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_cpm_scrape_profile_id_scrape_profiles",
        "competitor_product_matches",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_competitors_default_scrape_profile_id_scrape_profiles",
        "competitors",
        type_="foreignkey",
    )
    op.drop_table("scrape_profiles")
