"""scrape_jobs_targets_tables

Revision ID: a6b0234cd4ad
Revises: 2db33dea5e14
Create Date: 2026-07-03 00:00:00.000000

The two SPEC-08 tables (contracts/migration-jobs.md, data-model.md):
``scrape_jobs``, ``scrape_job_targets``. Both are workspace-owned — RLS
is enabled in this SAME migration for both (FR-004, §32, Principle II),
matching the SPEC-04/05/06/07 precedent.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.jobs`` exactly. Neither table is
partitioned; ``scrape_jobs`` carries ``unique(workspace_id, id)`` so
``scrape_job_targets`` can composite-FK its parent job workspace-locally
(``(workspace_id, scrape_job_id) -> scrape_jobs(workspace_id, id)``,
research D4 — the SPEC-05 ``competitor_product_matches`` precedent), so
a cross-workspace target->job reference is structurally impossible, not
just app-filtered. ``match_id`` (on both the job's soft scope refs and
the target) carries **no** FK (soft/deferred reference, §22 / SPEC-07
precedent). Both tables carry ``created_at`` only (no ``updated_at``,
§22).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'a6b0234cd4ad'
down_revision: Union[str, Sequence[str], None] = '2db33dea5e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create scrape_jobs + scrape_job_targets + RLS on both."""
    op.create_table(
        "scrape_jobs",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("product_group_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("match_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("total_targets", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scrape_jobs"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_scrape_jobs_workspace_id_id"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_scrape_jobs_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_scrape_jobs_workspace_id", "scrape_jobs", ["workspace_id"])

    op.create_table(
        "scrape_job_targets",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("scrape_job_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("match_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scrape_job_targets"),
        sa.UniqueConstraint(
            "scrape_job_id",
            "match_id",
            name="uq_scrape_job_targets_scrape_job_id_match_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "scrape_job_id"],
            ["scrape_jobs.workspace_id", "scrape_jobs.id"],
            name="fk_scrape_job_targets_workspace_scrape_job_scrape_jobs",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_scrape_job_targets_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_scrape_job_targets_workspace_id", "scrape_job_targets", ["workspace_id"]
    )
    op.create_index("ix_scrape_job_targets_match_id", "scrape_job_targets", ["match_id"])

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-004, §32, Principle II) — both tables.
    for statement in emit_rls_policy("scrape_jobs"):
        op.execute(statement)
    for statement in emit_rls_policy("scrape_job_targets"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the two tables in FK-safe order (targets -> jobs)."""
    op.drop_table("scrape_job_targets")
    op.drop_table("scrape_jobs")
