"""catalog_tables

Revision ID: c2987b29555e
Revises: 55da7d6d939d
Create Date: 2026-07-03 00:00:00.000000

The four SPEC-04 catalog tables (contracts/migration-catalog.md,
data-model.md): ``products``, ``product_variants``, ``product_groups``,
``product_group_items``. All four are workspace-owned — RLS is enabled
in this SAME migration for all four (FR-001, FR-003, §32, Principle II),
matching the SPEC-03 precedent (``55da7d6d939d``).

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.catalog`` exactly, honoring the
SPEC-02 ``NAMING_CONVENTION``. Workspace-local composite FKs
(``(workspace_id, ref_id) -> parent(workspace_id, id)``) make
cross-workspace references structurally impossible (D3) — the nullable
``product_group_items`` composite FKs to ``products``/``product_variants``
use ``MATCH SIMPLE`` so a NULL half of the pair is unchecked.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'c2987b29555e'
down_revision: Union[str, Sequence[str], None] = '55da7d6d939d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create the four catalog tables + RLS on all four."""
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_products"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_products_workspace_id_id"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_products_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_products_workspace_id", "products", ["workspace_id"])

    op.create_table(
        "product_variants",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("option_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_product_variants"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_product_variants_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id",
            "product_id",
            "title",
            name="uq_product_variants_workspace_id_product_id_title",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_product_variants_workspace_id_product_id_products",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_product_variants_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_product_variants_workspace_id", "product_variants", ["workspace_id"])

    op.create_table(
        "product_groups",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_product_groups"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_product_groups_workspace_id_id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_product_groups_workspace_id_name"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_product_groups_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_product_groups_workspace_id", "product_groups", ["workspace_id"])

    op.create_table(
        "product_group_items",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_group_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_product_group_items"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_group_id"],
            ["product_groups.workspace_id", "product_groups.id"],
            name="fk_product_group_items_workspace_id_group_id_product_groups",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_product_group_items_workspace_id_product_id_products",
            match="SIMPLE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_variant_id"],
            ["product_variants.workspace_id", "product_variants.id"],
            name="fk_product_group_items_workspace_id_variant_id_product_variants",
            match="SIMPLE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_product_group_items_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_product_group_items_workspace_id", "product_group_items", ["workspace_id"]
    )

    # Partial unique indexes (external_id/sku where present; group-item
    # membership where the corresponding ref is present) — FR-008.
    op.create_index(
        "uq_products_workspace_id_external_id",
        "products",
        ["workspace_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_index(
        "uq_products_workspace_id_sku",
        "products",
        ["workspace_id", "sku"],
        unique=True,
        postgresql_where=sa.text("sku IS NOT NULL"),
    )
    op.create_index(
        "uq_product_variants_workspace_id_external_id",
        "product_variants",
        ["workspace_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_index(
        "uq_product_variants_workspace_id_sku",
        "product_variants",
        ["workspace_id", "sku"],
        unique=True,
        postgresql_where=sa.text("sku IS NOT NULL"),
    )
    op.create_index(
        "uq_product_group_items_workspace_id_group_id_product_id",
        "product_group_items",
        ["workspace_id", "product_group_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("product_id IS NOT NULL"),
    )
    op.create_index(
        "uq_product_group_items_workspace_id_group_id_variant_id",
        "product_group_items",
        ["workspace_id", "product_group_id", "product_variant_id"],
        unique=True,
        postgresql_where=sa.text("product_variant_id IS NOT NULL"),
    )

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-001, FR-003, §32, Principle II) — all four catalog tables.
    for statement in emit_rls_policy("products"):
        op.execute(statement)
    for statement in emit_rls_policy("product_variants"):
        op.execute(statement)
    for statement in emit_rls_policy("product_groups"):
        op.execute(statement)
    for statement in emit_rls_policy("product_group_items"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the four catalog tables in FK-safe order."""
    op.drop_table("product_group_items")
    op.drop_table("product_variants")
    op.drop_table("product_groups")
    op.drop_table("products")
