"""control plane: control_plane_rules + workspace_entitlements.product_ceiling

Revision ID: c8d2e3f4a5b6
Revises: b7c1d2e3f4a5
Create Date: 2026-09-03

EPA C1. Two schema changes the SaaS control plane needs from the engine:

1. ``control_plane_rules`` — the workspace-owned record of *what the SaaS
   asked for* (a MONITOR/REPRICE rule on a named cadence, over a set of
   the SaaS's own external product ids), linked to the engine
   ``refresh_rules`` row that actually drives the scrape.
2. ``workspace_entitlements.product_ceiling`` — the nullable per-plan
   product cap the control plane's admission check reads.

Hand-authored (not autogenerated): there is no live Postgres connection
in this build environment. Column/constraint shapes reproduce
``app_shared.models.control_plane.ControlPlaneRule`` and the new
``WorkspaceEntitlement.product_ceiling`` column exactly. All SQL is
inlined here rather than imported from the live model modules — a
migration that imports today's constants stops describing the schema it
actually created the moment those constants change.

Why ``ON DELETE SET NULL`` on ``refresh_rule_id``
-------------------------------------------------
NOT ``CASCADE`` — the ondelete every scope-target FK on ``refresh_rules``
itself uses. The engine rule and the customer's request have different
lifetimes: engine machinery can retire, replace, or dead-letter a
``refresh_rules`` row knowing nothing about billing, and the record of
what the tenant asked for must survive that so an operator can still
answer "what did they ask for, and why is nothing running?". ``CASCADE``
would delete the evidence along with the mechanism.

Why ``product_ceiling`` is NULLABLE
-----------------------------------
``NULL`` means "no ceiling recorded" (an evidence row written before this
column existed, or a plan that does not express one) and must NOT be read
as a limit. ``0`` is a real, distinct value meaning "this plan allows
zero products". A ``NOT NULL DEFAULT 0`` would collapse the two and cap
every pre-existing workspace at zero the instant this migration ran.

Why the GRANT is ROLE-CONDITIONAL
---------------------------------
The API process runs as the ordinary ``crawmatic_app`` role, so the grant
is part of the migration rather than an operator step (the ``refresh_rules``
migration predates that convention; ``e92029e9902c`` established it). A
bare ``GRANT ... TO crawmatic_app`` ABORTS the whole ``alembic upgrade``
on any database where the role does not exist yet — a fresh CI database, a
scratch container, a first bootstrap — stopping every LATER revision too.
The ``DO $$ ... IF EXISTS (SELECT FROM pg_roles ...)`` wrapper keeps the
behaviour identical where the role exists and degrades to a ``NOTICE``
where it does not.

``downgrade()`` reverses everything: drops the entitlement column, the
workspace index, and the table (RLS/policy drop with the table).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'c8d2e3f4a5b6'
down_revision: Union[str, Sequence[str], None] = 'b7c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_GRANT_APP_ROLE = """
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'crawmatic_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON control_plane_rules
        TO crawmatic_app;
    ELSE
        RAISE NOTICE 'role crawmatic_app absent - skipping GRANT on '
                     'control_plane_rules (run '
                     'scripts/provision_db_roles.py before serving traffic)';
    END IF;
END $$;
"""


def upgrade() -> None:
    """Upgrade schema: create control_plane_rules (+RLS, +grant), add product_ceiling."""
    op.create_table(
        "control_plane_rules",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("cadence", sa.Text(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column(
            "target_external_ids",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("owner_tag", sa.Text(), nullable=True),
        sa.Column(
            "quarantined", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column("grace_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_rule_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_control_plane_rules"),
        sa.UniqueConstraint(
            "workspace_id",
            "external_id",
            name="uq_control_plane_rules_workspace_id_external_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_control_plane_rules_workspace_id_workspaces",
        ),
        sa.ForeignKeyConstraint(
            ["refresh_rule_id"],
            ["refresh_rules.id"],
            name="fk_control_plane_rules_refresh_rule_id_refresh_rules",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_control_plane_rules_workspace_id", "control_plane_rules", ["workspace_id"]
    )

    # RLS in the SAME migration that creates the workspace-owned table
    # (FR-005, §32, Principle II) — the identical emitter and policy shape
    # `refresh_rules` uses.
    for statement in emit_rls_policy("control_plane_rules"):
        op.execute(statement)

    op.execute(_GRANT_APP_ROLE)

    # The nullable per-plan product cap on the existing entitlement table.
    op.add_column(
        "workspace_entitlements",
        sa.Column("product_ceiling", sa.Integer(), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema: drop product_ceiling, then the index, then the table."""
    op.drop_column("workspace_entitlements", "product_ceiling")
    op.drop_index("ix_control_plane_rules_workspace_id", table_name="control_plane_rules")
    op.drop_table("control_plane_rules")
