"""outbox_messages

Revision ID: d4f1c07ae2b8
Revises: d3f7a6c11b84
Create Date: 2026-08-15 00:00:00.000000

NOTE ON ORDERING: this revision was authored against head
``b7d02a41c9e3`` but is chained behind ``d3f7a6c11b84``
(``proxy_breaker`` tables, the parallel audit-H3 work) so the history
stays single-headed. There is no dependency between the two — if
``d3f7a6c11b84`` is renamed or dropped, re-point ``down_revision`` at
``b7d02a41c9e3`` and re-run ``bash scripts/check_single_head.sh``.

The single table behind the 2026-08-15 audit's risk **H1** fix
(CORE_PRODUCT_PRODUCTION_READINESS_AUDIT_2026-08-15 §H1/§11): a
transactional outbox. Producers that previously committed domain data and
then fired a Celery task now write one ``outbox_messages`` row in the
SAME transaction as the domain write; the drain pass
(``app_shared.outbox.dispatcher``) publishes it afterwards with
at-least-once delivery and bounded retries.

Workspace-owned — RLS is enabled in this SAME migration (§32, Principle
II), matching the SPEC-04..16 precedent. Producers write the table under
the ordinary workspace-scoped session (that is the point: same
transaction as the domain data), so the policy is a real isolation
surface, not a formality; the cross-tenant drain/reconcile passes run on
the sanctioned BYPASSRLS system session like ``run_refresh_pass``.

**Deliberately NOT partitioned.** Every other high-volume table here
(``price_observations``/``request_attempts``/``price_alert_events``/
``webhook_events``) is monthly-partitioned because it is append-only
history read by time range. This one is a drain-to-empty *work queue*:
its steady-state size is the unpublished backlog, its hot path is a
``FOR UPDATE SKIP LOCKED`` claim over a small partial index, and its
retention is deleting terminal rows (``app_shared.outbox.reconciler``,
scheduled beside the SPEC-15 passes), not dropping a month. Partition
pruning would add cost to the claim and reclaim nothing. It is therefore
also absent from ``app_shared.maintenance.registry.PARTITIONED_TABLES``.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint shapes
reproduce ``app_shared.models.outbox.OutboxMessage`` exactly:

* ``ix_outbox_messages_claim`` — partial on ``status = 'PENDING'``, over
  ``(available_at, id)``: exactly the drain's claim/ordering predicate,
  and proportional to the backlog rather than to history (mirrors
  ``ix_refresh_rules_due``).
* ``ix_outbox_messages_pending_dedup`` — **partial UNIQUE** on
  ``(workspace_id, dedup_key)`` where ``status = 'PENDING'``: at most one
  *unpublished* copy of a logical message, so a producer sweep that
  re-runs before the drain catches up cannot double-publish. Partial
  rather than a plain unique constraint because dedup keys such as
  ``strategy:{profile}:{status}:{change}`` legitimately recur later; a
  permanent constraint would silently swallow the genuine later event.
  Producers insert with ``ON CONFLICT DO NOTHING`` against this index, so
  a collision can never abort the caller's domain transaction.
* ``ix_outbox_messages_status_updated_at`` — retention + operator
  dashboards.

Only ``workspace_id`` carries a real FK (the RLS anchor); everything the
payload references is a soft reference (§22), matching
``webhook_events.payload``.

``downgrade()`` drops the table (its indexes/policy go with it).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = "d4f1c07ae2b8"
down_revision: Union[str, Sequence[str], None] = "d3f7a6c11b84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PENDING_PREDICATE = "status = 'PENDING'"


def upgrade() -> None:
    """Upgrade schema: create outbox_messages, its three indexes, and RLS."""
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column("queue", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_outbox_messages"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_outbox_messages_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_outbox_messages_workspace_id", "outbox_messages", ["workspace_id"]
    )
    op.create_index(
        "ix_outbox_messages_claim",
        "outbox_messages",
        ["available_at", "id"],
        postgresql_where=sa.text(_PENDING_PREDICATE),
    )
    op.create_index(
        "ix_outbox_messages_pending_dedup",
        "outbox_messages",
        ["workspace_id", "dedup_key"],
        unique=True,
        postgresql_where=sa.text(_PENDING_PREDICATE),
    )
    op.create_index(
        "ix_outbox_messages_status_updated_at",
        "outbox_messages",
        ["status", "updated_at"],
    )

    # RLS in the SAME migration that creates the workspace-owned table
    # (§32, Principle II).
    for statement in emit_rls_policy("outbox_messages"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop outbox_messages (indexes/policy drop with it)."""
    op.drop_index("ix_outbox_messages_status_updated_at", table_name="outbox_messages")
    op.drop_index("ix_outbox_messages_pending_dedup", table_name="outbox_messages")
    op.drop_index("ix_outbox_messages_claim", table_name="outbox_messages")
    op.drop_index("ix_outbox_messages_workspace_id", table_name="outbox_messages")
    op.drop_table("outbox_messages")
