"""alerts_price_states_tables

Revision ID: e4a75b48360c
Revises: a6b0234cd4ad
Create Date: 2026-07-03 00:00:00.000000

The three SPEC-09 tables (contracts/migration-alerts.md, data-model.md):
``variant_price_states`` + ``variant_alert_states`` (both current-state,
not partitioned) and ``price_alert_events`` (**monthly-partitioned by
``created_at`` from birth**, mirroring the SPEC-07 ``price_observations``
precedent, research D3, Constitution §22/§29). All three are
workspace-owned — RLS is enabled in this SAME migration for all three
(FR-005, §32, Principle II), matching the SPEC-04..08 precedent.

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.alerts`` exactly. The partitioned
parent declares ``postgresql_partition_by`` (rendering ``PARTITION BY
RANGE (...)``) with a composite primary key that includes the partition
column (Postgres's rule for partitioned tables); current + next month
``PARTITION OF`` children are created via raw ``op.execute`` (no
``op.create_table`` support for partition children) using the same
``_month_partition_bounds`` helper copied verbatim from
``2db33dea5e14_observations_current_prices_tables.py``. RLS applied to a
partitioned **parent** propagates to its partitions, so it is only
emitted once per parent, not per partition. ``product_id``/
``product_variant_id``/``alert_state_id``/``latest_alert_state_id`` all
carry **no** FK (soft/deferred references, §22); only ``workspace_id``
gets a real FK (the RLS anchor).
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'e4a75b48360c'
down_revision: Union[str, Sequence[str], None] = 'a6b0234cd4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _month_partition_bounds(base: datetime) -> list[tuple[str, str, str]]:
    """Return ``[(suffix, start_date, end_date_exclusive), ...]`` for
    ``base``'s month and the following month (current + next, per
    contracts/migration-alerts.md), each as ``YYYY-MM-01`` ISO date
    strings. ``suffix`` is ``YYYY_MM`` (< 63-byte partition table name
    budget once prefixed with ``price_alert_events_``). Copied verbatim
    from ``2db33dea5e14_observations_current_prices_tables.py``.
    """
    bounds: list[tuple[str, str, str]] = []
    year, month = base.year, base.month
    for offset in range(2):
        m = month + offset
        y = year
        if m > 12:
            m -= 12
            y += 1
        start = f"{y:04d}-{m:02d}-01"
        next_m = m + 1
        next_y = y
        if next_m > 12:
            next_m = 1
            next_y += 1
        end = f"{next_y:04d}-{next_m:02d}-01"
        bounds.append((f"{y:04d}_{m:02d}", start, end))
    return bounds


def upgrade() -> None:
    """Upgrade schema: create the two current-state tables, the
    partitioned price_alert_events parent + initial partitions, and RLS
    (ENABLE+FORCE+fail-closed) on all three."""
    now = datetime.now(timezone.utc)

    # --- variant_price_states (current-state, NOT partitioned) --------------
    op.create_table(
        "variant_price_states",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("client_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("cheapest_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("average_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("highest_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("comparable_competitor_count", sa.Integer(), nullable=False),
        sa.Column("latest_alert_type", sa.String(length=32), nullable=False),
        sa.Column("latest_alert_severity", sa.String(length=32), nullable=False),
        sa.Column("latest_alert_state_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_variant_price_states"),
        sa.UniqueConstraint(
            "workspace_id",
            "product_variant_id",
            name="uq_variant_price_states_workspace_id_product_variant_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_variant_price_states_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_variant_price_states_workspace_id", "variant_price_states", ["workspace_id"]
    )

    # --- variant_alert_states (current-state, NOT partitioned) ---------------
    op.create_table(
        "variant_alert_states",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("client_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("benchmark_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("cheapest_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("average_competitor_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_variant_alert_states"),
        sa.UniqueConstraint(
            "workspace_id",
            "product_variant_id",
            name="uq_variant_alert_states_workspace_id_product_variant_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_variant_alert_states_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_variant_alert_states_workspace_id", "variant_alert_states", ["workspace_id"]
    )
    op.create_index(
        "ix_variant_alert_states_workspace_id_type",
        "variant_alert_states",
        ["workspace_id", "type"],
    )
    op.create_index(
        "ix_variant_alert_states_workspace_id_severity",
        "variant_alert_states",
        ["workspace_id", "severity"],
    )

    # --- price_alert_events (PARTITIONED by created_at) ----------------------
    op.create_table(
        "price_alert_events",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("alert_state_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("previous_type", sa.String(length=32), nullable=True),
        sa.Column("new_type", sa.String(length=32), nullable=False),
        sa.Column("previous_severity", sa.String(length=32), nullable=True),
        sa.Column("new_severity", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(), nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at", name="pk_price_alert_events"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_price_alert_events_workspace_id_workspaces",
        ),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "ix_price_alert_events_workspace_id", "price_alert_events", ["workspace_id"]
    )
    op.create_index(
        "ix_price_alert_events_product_variant_id",
        "price_alert_events",
        ["product_variant_id"],
    )

    for suffix, start, end in _month_partition_bounds(now):
        op.execute(
            f"CREATE TABLE price_alert_events_{suffix} PARTITION OF price_alert_events "
            f"FOR VALUES FROM ('{start}') TO ('{end}');"
        )

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-005, §32, Principle II) — all three. Applying RLS to a
    # partitioned parent propagates to its partitions (current +
    # future), so this is emitted once per parent, not per partition.
    for table in ("variant_price_states", "variant_alert_states", "price_alert_events"):
        for statement in emit_rls_policy(table):
            op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the two current-state tables, then each
    price_alert_events partition + parent (reverse of creation order)."""
    now = datetime.now(timezone.utc)

    op.drop_table("variant_alert_states")
    op.drop_table("variant_price_states")

    for suffix, _start, _end in _month_partition_bounds(now):
        op.execute(f"DROP TABLE IF EXISTS price_alert_events_{suffix};")
    op.drop_table("price_alert_events")
