"""domain_strategy_optimizer_tables

Revision ID: f30c60cfa2f7
Revises: 851220acab90
Create Date: 2026-07-05 00:00:00.000000

The three SPEC-12 tables (contracts/rls-and-migration.md, data-model.md):
``domain_strategy_profiles``, ``strategy_attempt_stats``,
``strategy_discovery_runs`` — the learned/rolled-up access+extraction
strategy layer, not partitioned (§29, the rolled-up layer, not
append-heavy audit). RLS is enabled in this SAME migration:
``emit_rls_policy`` for the two workspace-owned tables
(``domain_strategy_profiles``, ``strategy_discovery_runs``) and the
**new** ``emit_fk_transitive_rls_policy`` for ``strategy_attempt_stats``
(no ``workspace_id`` column of its own — isolated transitively via its
FK to ``domain_strategy_profiles``, research D3), matching the
SPEC-04..11 precedent of emitting RLS alongside table creation.

Workspace-local composite FKs (``(workspace_id, competitor_id) ->
competitors(workspace_id, id)``) on the two workspace-owned tables make
a cross-workspace competitor reference structurally impossible, not
just app-filtered (the SPEC-05 ``competitor_product_matches`` /
research D4 pattern). Several convention-generated names for this table
set would exceed Postgres's 63-byte identifier cap, so those use the
explicit ``dsp``/``sas``/``sdr`` shorthands (the ``cpm`` precedent).

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.strategy`` exactly.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app_shared.models import emit_fk_transitive_rls_policy, emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'f30c60cfa2f7'
down_revision: Union[str, Sequence[str], None] = '851220acab90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create the 3 domain-strategy-optimizer tables + RLS on all three."""

    # --- domain_strategy_profiles (WORKSPACE-OWNED) --------------------
    op.create_table(
        "domain_strategy_profiles",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("url_pattern", sa.Text(), nullable=False),
        sa.Column("url_pattern_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("preferred_access_method", sa.String(length=32), nullable=True),
        sa.Column("preferred_extraction_method", sa.String(length=32), nullable=True),
        sa.Column("access_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("confirmed_success_count", sa.Integer(), nullable=False),
        sa.Column("recent_failure_count", sa.Integer(), nullable=False),
        sa.Column("last_discovery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_domain_strategy_profiles"),
        sa.UniqueConstraint(
            "workspace_id",
            "competitor_id",
            "domain",
            "url_pattern",
            name="uq_dsp_ws_competitor_domain_pattern",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "competitor_id"],
            ["competitors.workspace_id", "competitors.id"],
            name="fk_dsp_workspace_competitor_competitors",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_domain_strategy_profiles_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_domain_strategy_profiles_workspace_id",
        "domain_strategy_profiles",
        ["workspace_id"],
    )
    op.create_index(
        "ix_dsp_ws_competitor_domain_pattern_version",
        "domain_strategy_profiles",
        ["workspace_id", "competitor_id", "domain", "url_pattern", "url_pattern_version"],
    )

    # --- strategy_attempt_stats (NO workspace_id — transitive RLS) -----
    op.create_table(
        "strategy_attempt_stats",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("domain_strategy_profile_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("method_type", sa.String(length=32), nullable=False),
        sa.Column("method_name", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("avg_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("avg_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_strategy_attempt_stats"),
        sa.UniqueConstraint(
            "domain_strategy_profile_id",
            "method_type",
            "method_name",
            name="uq_sas_profile_method_type_name",
        ),
        sa.ForeignKeyConstraint(
            ["domain_strategy_profile_id"],
            ["domain_strategy_profiles.id"],
            name="fk_sas_profile_id_domain_strategy_profiles",
        ),
    )
    op.create_index(
        "ix_strategy_attempt_stats_domain_strategy_profile_id",
        "strategy_attempt_stats",
        ["domain_strategy_profile_id"],
    )

    # --- strategy_discovery_runs (WORKSPACE-OWNED) ---------------------
    op.create_table(
        "strategy_discovery_runs",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("url_pattern", sa.Text(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("winning_access_method", sa.String(length=32), nullable=True),
        sa.Column("winning_extraction_method", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_strategy_discovery_runs"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "competitor_id"],
            ["competitors.workspace_id", "competitors.id"],
            name="fk_sdr_workspace_competitor_competitors",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_strategy_discovery_runs_workspace_id_workspaces",
        ),
    )
    op.create_index(
        "ix_strategy_discovery_runs_workspace_id",
        "strategy_discovery_runs",
        ["workspace_id"],
    )
    op.create_index(
        "ix_sdr_ws_competitor_domain_pattern",
        "strategy_discovery_runs",
        ["workspace_id", "competitor_id", "domain", "url_pattern"],
    )

    # RLS in the SAME migration that creates the tables (§32, Principle II):
    # standard fail-closed isolation for the two workspace-owned tables,
    # transitive (EXISTS-via-parent) isolation for strategy_attempt_stats
    # (no workspace_id column of its own, research D3, FR-026).
    for statement in emit_rls_policy("domain_strategy_profiles"):
        op.execute(statement)
    for statement in emit_fk_transitive_rls_policy(
        "strategy_attempt_stats",
        parent_table="domain_strategy_profiles",
        fk_column="domain_strategy_profile_id",
    ):
        op.execute(statement)
    for statement in emit_rls_policy("strategy_discovery_runs"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the 3 tables in reverse creation order."""
    op.drop_table("strategy_discovery_runs")
    op.drop_table("strategy_attempt_stats")
    op.drop_table("domain_strategy_profiles")
