"""competitors_matches_tables

Revision ID: f4c8a391d5c9
Revises: c2987b29555e
Create Date: 2026-07-03 00:00:00.000000

The two SPEC-05 tables (contracts/migration-competitors-matches.md,
data-model.md): ``competitors``, ``competitor_product_matches``. Both
are workspace-owned — RLS is enabled in this SAME migration for both
(FR-001, FR-002, §32, Principle II), matching the SPEC-04 precedent
(``c2987b29555e``).

Hand-authored (not autogenerated) because there is no live Postgres
connection available in this build environment. Column/constraint
shapes reproduce ``app_shared.models.competitors_matches`` exactly,
honoring the SPEC-02 ``NAMING_CONVENTION`` for ``competitors`` and the
explicit ``cpm`` (competitor_product_matches) names for
``competitor_product_matches`` (research D5 — the convention-generated
names for this table's 4-column unique and composite FKs would exceed
Postgres's 63-byte identifier cap). Workspace-local composite FKs
(``(workspace_id, ref_id) -> parent(workspace_id, id)``) on the match
make cross-workspace references structurally impossible (research D4).
``current_price_id``/``scrape_profile_id``/``access_policy_id`` carry
**no** FK (soft/deferred references, targets SPEC-06/09/10).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app_shared.models import emit_rls_policy

# revision identifiers, used by Alembic.
revision: str = 'f4c8a391d5c9'
down_revision: Union[str, Sequence[str], None] = 'c2987b29555e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create the two competitors/matches tables + RLS on both."""
    op.create_table(
        "competitors",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("legal_status", sa.String(length=32), nullable=False),
        sa.Column("robots_policy", sa.String(length=32), nullable=False),
        sa.Column("default_scrape_profile_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("default_access_policy_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("max_concurrent_requests", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_minute", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_competitors"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_competitors_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "domain", name="uq_competitors_workspace_id_domain"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_competitors_workspace_id_workspaces",
        ),
    )
    op.create_index("ix_competitors_workspace_id", "competitors", ["workspace_id"])

    op.create_table(
        "competitor_product_matches",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("workspace_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("product_variant_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("competitor_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("competitor_url", sa.Text(), nullable=False),
        sa.Column("normalized_competitor_url", sa.Text(), nullable=False),
        sa.Column("url_pattern", sa.Text(), nullable=False),
        sa.Column("url_pattern_version", sa.Integer(), nullable=False),
        sa.Column("competitor_variant_identifier", sa.Text(), nullable=True),
        sa.Column("competitor_variant_sku", sa.Text(), nullable=True),
        sa.Column(
            "competitor_variant_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("external_title", sa.Text(), nullable=True),
        sa.Column("scrape_profile_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("access_policy_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("success_rate_7d", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("current_price_id", sa.Uuid(as_uuid=True), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_competitor_product_matches"),
        sa.UniqueConstraint(
            "workspace_id",
            "product_variant_id",
            "competitor_id",
            "normalized_competitor_url",
            name="uq_cpm_ws_variant_competitor_norm_url",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_cpm_workspace_product_products",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_variant_id"],
            ["product_variants.workspace_id", "product_variants.id"],
            name="fk_cpm_workspace_variant_variants",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "competitor_id"],
            ["competitors.workspace_id", "competitors.id"],
            name="fk_cpm_workspace_competitor_competitors",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="fk_cpm_workspace_workspaces",
        ),
    )
    op.create_index(
        "ix_competitor_product_matches_workspace_id",
        "competitor_product_matches",
        ["workspace_id"],
    )

    # RLS in the SAME migration that creates the workspace-owned tables
    # (FR-001, FR-002, §32, Principle II) — both tables.
    for statement in emit_rls_policy("competitors"):
        op.execute(statement)
    for statement in emit_rls_policy("competitor_product_matches"):
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema: drop the two tables in FK-safe order (matches -> competitors)."""
    op.drop_table("competitor_product_matches")
    op.drop_table("competitors")
