"""Offline migration render test (FR-013, FR-014, SC-003 end-to-end).

Runs ``alembic upgrade head --sql`` (offline mode — no DB connection,
see ``alembic/env.py``) via subprocess and asserts the rendered SQL
proves every SPEC-02 primitive the first migration exercises:

* ``CREATE TABLE`` for the demo ``_smoke_foundation`` table,
* ``TIMESTAMPTZ``-equivalent columns (``TIMESTAMP WITH TIME ZONE``),
* the ``NUMERIC(18, 4)`` money column,
* the ``uuid`` primary key type,
* both DISTINCT unique-constraint names generated by the naming
  convention for the two multi-column uniques sharing the leading
  ``group_key`` column (FR-002, SC-003) — never colliding.

Also asserts ``alembic heads`` reports exactly ONE head (FR-012,
SC-006) — the single-linear-history guarantee this migration's
authoring must not violate.

DB-independent: this test never opens a Postgres connection (see
``alembic/env.py::run_migrations_offline``).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def _run_alembic(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=60,
    )


def test_offline_upgrade_head_renders_smoke_foundation_ddl() -> None:
    """`alembic upgrade head --sql` renders the full _smoke_foundation DDL, no DB needed."""
    result = _run_alembic("upgrade", "head", "--sql")

    assert result.returncode == 0, (
        f"alembic upgrade head --sql failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )

    sql = result.stdout

    assert "CREATE TABLE _smoke_foundation" in sql
    assert "TIMESTAMP WITH TIME ZONE" in sql
    assert "NUMERIC(18, 4)" in sql
    assert "UUID" in sql.upper()

    # Both distinct unique-constraint names — the disambiguation proof
    # (FR-002, SC-003): two multi-column uniques sharing the leading
    # `group_key` column must NOT collide on a single name.
    assert "uq__smoke_foundation_group_key_code_a" in sql
    assert "uq__smoke_foundation_group_key_code_b" in sql


def test_alembic_heads_reports_exactly_one_head() -> None:
    """`alembic heads` reports exactly one head (FR-012, SC-006)."""
    result = _run_alembic("heads")

    assert result.returncode == 0, (
        f"alembic heads failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )

    head_lines = [line for line in result.stdout.strip().splitlines() if line.strip()]
    assert len(head_lines) == 1, f"expected exactly one head, got: {head_lines!r}"
    assert "(head)" in head_lines[0]
